---
- name: restart hadoop master services
  service: name={{item}} state=restarted
  become: True
  with_items:
    - hadoop-0.20-mapreduce-jobtracker
    - hadoop-hdfs-namenode

- name: restart hadoopha master services
  service: name={{item}} state=restarted
  with_items:
    - hadoop-0.20-mapreduce-jobtrackerha
    - hadoop-hdfs-namenode
