---
- name: Install the qjournal package
  yum: name=hadoop-hdfs-journalnode state=installed

- name: Create folder for journaling
  file: path={{ hadoop.dfs_journalnode_edits_dir }} state=directory owner=hdfs group=hdfs

- name: Copy the hadoop configuration files
  template: src=roles/templates/{{ item }}.j2 dest=/etc/hadoop/conf/{{ item }}
  with_items:
   - core-site.xml
   - hadoop-metrics.properties
   - hadoop-metrics2.properties
   - hdfs-site.xml
   - log4j.properties
   - mapred-site.xml
   - slaves
  notify: restart qjournal services
