---
- include: common.yml

- name: Config for `master` node
  hosts: masters
  become: True

  roles:
    - { role: 'hadoop/roles/common' }
    - { role: 'hadoop/roles/zookeeper_servers' }
    - { role: 'hadoop/roles/qjournal_servers' }
    #- { role: 'hadoop/roles/master' }
    #- hue
